# Moving Average Forecast (3, 5 and 7 periods)

### Import Packages

In [1]:
import pandas as pd
import numpy as np

### Import Data

In [2]:
df = pd.DataFrame()
df_moving_avg_3_period = pd.DataFrame()
df_moving_avg_5_period = pd.DataFrame()
df_moving_avg_7_period = pd.DataFrame()


df['X'] = [1,2,3,4,5,6,7,8,9,10]
df['Values'] = [2,4,6,8,10,12,14,16,18,20]
df['Time'] = ['2018-01-01','2018-02-01','2018-03-01','2018-04-01','2018-05-01','2018-06-01','2018-07-01','2018-08-01','2018-09-01','2018-10-01']

df_moving_avg_3_period['X'] = df['X']
df_moving_avg_3_period['Values'] = df['Values']
df_moving_avg_3_period['Time'] = df['Time']

df_moving_avg_5_period['X'] = df['X']
df_moving_avg_5_period['Values'] = df['Values']
df_moving_avg_5_period['Time'] = df['Time']

df_moving_avg_7_period['X'] = df['X']
df_moving_avg_7_period['Values'] = df['Values']
df_moving_avg_7_period['Time'] = df['Time']

## 3 Periods

In [3]:
current_pos = 0
period_3 = [0,0,0]

for row in df_moving_avg_3_period.iterrows():
    next_pos = current_pos + 1
    last_pos = next_pos + 1
    
    try:
        if current_pos < len(df_moving_avg_3_period) and next_pos < len(df_moving_avg_3_period) and last_pos < len(df_moving_avg_3_period):
            sum_values = df_moving_avg_3_period.iloc[current_pos]['Values'] + df_moving_avg_3_period.iloc[current_pos + 1]['Values'] + df_moving_avg_3_period.iloc[current_pos + 2]['Values']
            period_3.append((sum_values/3))
    
    except Exception as e:
        print('broke because: ' + str(e))
    
    current_pos+=1
    
df_moving_avg_3_period['Forecasted Values (3 Period)'] = period_3[:len(df_moving_avg_3_period)]

## 5 Periods

In [4]:
current_pos = 0
period_5 = [0,0,0,0,0]

for row in df_moving_avg_5_period.iterrows():
    try:
        if current_pos + 4 < len(df_moving_avg_5_period):
            sum_values = df_moving_avg_5_period.iloc[current_pos]['Values'] + df_moving_avg_5_period.iloc[current_pos + 1]['Values'] + df_moving_avg_5_period.iloc[current_pos + 2]['Values'] + df_moving_avg_5_period.iloc[current_pos + 3]['Values'] + df_moving_avg_5_period.iloc[current_pos + 4]['Values']

            period_5.append(sum_values/5)
    
    except Exception as e:
        print('broke because: {}'.format(e))
    
    current_pos+=1
    
df_moving_avg_5_period['Forecasted Values (5 Period)'] = period_5[:len(df_moving_avg_5_period)]

## 7 Periods

In [5]:
current_pos = 0
period_7 = [0,0,0,0,0,0,0]

for row in df_moving_avg_7_period.iterrows():
    try:
        if current_pos + 6 < len(df_moving_avg_7_period):
            sum_values = df_moving_avg_7_period.iloc[current_pos]['Values'] + df_moving_avg_7_period.iloc[current_pos + 1]['Values'] + df_moving_avg_7_period.iloc[current_pos + 2]['Values'] + df_moving_avg_7_period.iloc[current_pos + 3]['Values'] + df_moving_avg_7_period.iloc[current_pos + 4]['Values'] + df_moving_avg_7_period.iloc[current_pos + 5]['Values'] + df_moving_avg_7_period.iloc[current_pos + 6]['Values']

            period_7.append(sum_values/7)
    
    except Exception as e:
        print('broke because: {}'.format(e))

    current_pos+=1
    
df_moving_avg_7_period['Forecasted Values (7 Period)'] = period_7[:len(df_moving_avg_7_period)]

### Calculate Errors for 3 Periods

In [8]:
list_error = []
list_error_squared = []
list_error_actual = []
list_variance = []
list_demand_forecast = []

sum_error = 0
sum_error_squared = 0
sum_error_actual = 0
sum_demand_forecast = 0

for row in df_moving_avg_3_period.iterrows():
    pred = int(row[1]['Forecasted Values (3 Period)'])
    value = int(row[1]['Values'])
    
    mean_y = df_moving_avg_3_period['Values'].mean()
    
    error = pred - value
    square_error = error**2
    variance = (pred - mean_y)**2
    error_actual = error / value
    error_dem = value - pred
    
    sum_demand_forecast += error_dem
    sum_error += error
    sum_error_squared += square_error
    sum_error_actual += error_actual
    
    list_error.append(error)
    list_error_squared.append(square_error)
    list_variance.append(variance)
    list_error_actual.append(error_actual)
    list_demand_forecast.append(error_dem)
    
df_moving_avg_3_period["Error"] = list_error
df_moving_avg_3_period["Squared Error"] = list_error_squared
df_moving_avg_3_period["Error/Actual"] = list_error_actual
df_moving_avg_3_period["Forecasted - mean(y)"] = list_variance
df_moving_avg_3_period["Residuals"] = list_demand_forecast

### Calculate Errors for 5 Periods

In [9]:
list_error = []
list_error_squared = []
list_error_actual = []
list_variance = []
list_demand_forecast = []

sum_error = 0
sum_error_squared = 0
sum_error_actual = 0
sum_demand_forecast = 0

for row in df_moving_avg_5_period.iterrows():
    pred = int(row[1]['Forecasted Values (5 Period)'])
    value = int(row[1]['Values'])
    
    mean_y = df_moving_avg_5_period['Values'].mean()
    
    error = pred - value
    square_error = error**2
    variance = (pred - mean_y)**2
    error_actual = error / value
    error_dem = value - pred
    
    sum_demand_forecast += error_dem
    sum_error += error
    sum_error_squared += square_error
    sum_error_actual += error_actual
    
    list_error.append(error)
    list_error_squared.append(square_error)
    list_variance.append(variance)
    list_error_actual.append(error_actual)
    list_demand_forecast.append(error_dem)
    
df_moving_avg_5_period["Error"] = list_error
df_moving_avg_5_period["Squared Error"] = list_error_squared
df_moving_avg_5_period["Error/Actual"] = list_error_actual
df_moving_avg_5_period["Forecasted - mean(y)"] = list_variance
df_moving_avg_5_period["Residuals"] = list_demand_forecast

### Calculate Errors for 7 Periods

In [13]:
list_error = []
list_error_squared = []
list_error_actual = []
list_variance = []
list_demand_forecast = []

sum_error = 0
sum_error_squared = 0
sum_error_actual = 0
sum_demand_forecast = 0

for row in df_moving_avg_7_period.iterrows():
    pred = int(row[1]['Forecasted Values (7 Period)'])
    value = int(row[1]['Values'])
    
    mean_y = df_moving_avg_7_period['Values'].mean()
    
    error = pred - value
    square_error = error**2
    variance = (pred - mean_y)**2
    error_actual = error / value
    error_dem = value - pred
    
    sum_demand_forecast += error_dem
    sum_error += error
    sum_error_squared += square_error
    sum_error_actual += error_actual
    
    list_error.append(error)
    list_error_squared.append(square_error)
    list_variance.append(variance)
    list_error_actual.append(error_actual)
    list_demand_forecast.append(error_dem)
    
df_moving_avg_7_period["Error"] = list_error
df_moving_avg_7_period["Squared Error"] = list_error_squared
df_moving_avg_7_period["Error/Actual"] = list_error_actual
df_moving_avg_7_period["Forecasted - mean(y)"] = list_variance
df_moving_avg_7_period["Residuals"] = list_demand_forecast

In [10]:
df_moving_avg_3_period

,X,Values,Time,Forecasted Values (3 Period),Error,Squared Error,Error/Actual,Forecasted - mean(y),Residuals
0,1,2,2018-01-01,0.0,-2,4,-1.000000,121.0,2
1,2,4,2018-02-01,0.0,-4,16,-1.000000,121.0,4
2,3,6,2018-03-01,0.0,-6,36,-1.000000,121.0,6
3,4,8,2018-04-01,4.0,-4,16,-0.500000,49.0,4
4,5,10,2018-05-01,6.0,-4,16,-0.400000,25.0,4
5,6,12,2018-06-01,8.0,-4,16,-0.333333,9.0,4
6,7,14,2018-07-01,10.0,-4,16,-0.285714,1.0,4
7,8,16,2018-08-01,12.0,-4,16,-0.250000,1.0,4
8,9,18,2018-09-01,14.0,-4,16,-0.222222,9.0,4
9,10,20,2018-10-01,16.0,-4,16,-0.200000,25.0,4

In [11]:
df_moving_avg_5_period

,X,Values,Time,Forecasted Values (5 Period),Error,Squared Error,Error/Actual,Forecasted - mean(y),Residuals
0,1,2,2018-01-01,0.0,-2,4,-1.000000,121.0,2
1,2,4,2018-02-01,0.0,-4,16,-1.000000,121.0,4
2,3,6,2018-03-01,0.0,-6,36,-1.000000,121.0,6
3,4,8,2018-04-01,0.0,-8,64,-1.000000,121.0,8
4,5,10,2018-05-01,0.0,-10,100,-1.000000,121.0,10
5,6,12,2018-06-01,6.0,-6,36,-0.500000,25.0,6
6,7,14,2018-07-01,8.0,-6,36,-0.428571,9.0,6
7,8,16,2018-08-01,10.0,-6,36,-0.375000,1.0,6
8,9,18,2018-09-01,12.0,-6,36,-0.333333,1.0,6
9,10,20,2018-10-01,14.0,-6,36,-0.300000,9.0,6

In [14]:
df_moving_avg_7_period

,X,Values,Time,Forecasted Values (7 Period),Error,Squared Error,Error/Actual,Forecasted - mean(y),Residuals
0,1,2,2018-01-01,0.0,-2,4,-1.000000,121.0,2
1,2,4,2018-02-01,0.0,-4,16,-1.000000,121.0,4
2,3,6,2018-03-01,0.0,-6,36,-1.000000,121.0,6
3,4,8,2018-04-01,0.0,-8,64,-1.000000,121.0,8
4,5,10,2018-05-01,0.0,-10,100,-1.000000,121.0,10
5,6,12,2018-06-01,0.0,-12,144,-1.000000,121.0,12
6,7,14,2018-07-01,0.0,-14,196,-1.000000,121.0,14
7,8,16,2018-08-01,8.0,-8,64,-0.500000,9.0,8
8,9,18,2018-09-01,10.0,-8,64,-0.444444,1.0,8
9,10,20,2018-10-01,12.0,-8,64,-0.400000,1.0,8